# Generated by Django 5.2.4 on 2025-07-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Compétence')),
                ('categorie', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de Données'), ('devops', 'DevOps'), ('outil', 'Outil'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('sujet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sujet du Message')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de Soumission')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du Projet')),
                ('description', models.TextField(verbose_name='Description Détaillée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/', verbose_name='Image du Projet')),
                ('url_demo', models.URLField(blank=True, null=True, verbose_name='URL de Démonstration')),
                ('url_github', models.URLField(blank=True, null=True, verbose_name='URL GitHub')),
                ('technologies_utilisee', models.CharField(max_length=255, verbose_name='Technologies Utilisées (ex: Django, React, PostgreSQL)')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de Création')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name="Mettre en Avant sur la Page d'Accueil")),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
